### ISSUE TITLE
Need the ability to delete a product from the catalog

### ISSUE THREAD

**Issue by Sayrikey1** [Sayrikey1/LeadsTracker#4]
**As a** User
 **I need** the a delete button
 **So that** I can delete products in catalog
   
 ### Details and Assumptions
 * Make a delete button
 * Remove the product from the database
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I'm on a product page
 When I click on delete
 Then the product should get deleted
 ```

**Comment by HadrielWonda** [comment]
you can create the button on the product page by including


<form action="/delete/:id" method="post">
<button type='submit' class="btn btn-lg">Delete</button>
</form>








then in your node:

app.post('/delete/:id', (req, res) => {
  Post.deleteOne((err) => {
    if (!err) {
      res.redirect('/')
    }
  })
});



to delete information from your database as well as delete the page

**Comment by Sayrikey1** [comment]
This was the repo i used for learning.. They're not real issues.. But oh well.
