### ISSUE TITLE
Need the ability to "Like" a product in the catalog

### ISSUE THREAD

**Issue by Sayrikey1** [Sayrikey1/LeadsTracker#5]
**As a** User
 **I need** a button 
 **So that** I can like certain products
   
 ### Details and Assumptions
 * Each product should have an option to like
 * You can enable button with HTML
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I am on the product page
 When I click the like button
 Then product should reflect it has been liked.
 ```

**Comment by HadrielWonda** [comment]
I feel it's best to make it an onclick function ie a likeicon button 

<a class="likeicon" userId="<%= newUsers._id %>" onclink="updateLikes()">
   <i class="fa fa-thumbs-o-up" aria-hidden="true" > 49 </i>
</a>


then your function can be like;


function updateLikes() {
    id = $('.likeicon').attr('userId');
    $.post('/index/' + id, function (response) {
        $('fa-thumbs-o-up').text(response.likeCount); //your counter on a page
        //and update likes and count in accordance    })
}

and your node end can be like:

app.post("/index/:id", function (req, res) {
    TestData.findById(req.params.id, function (err, theUser) {
        if (err) {
            console.log(err);
        } else {
            theUser.likes += 1;
            theUser.save();
            console.log(theUser.likes);
            res.send({likeCount: theUser.likes}); //or something like this if you get me...
        }
    });
});
