### ISSUE TITLE
Need the ability to list all products in the catalog

### ISSUE THREAD

**Issue by Sayrikey1** [Sayrikey1/LeadsTracker#7]
**As a** [role]  
 **I need** [function]  
 **So that** [benefit]  
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by HadrielWonda** [comment]
Doing this manually can be tasking so I'd suggest you look through Stripe's API documentation [https://stripe.com/docs/api/products/list?lang=node](url)
